services:
  app:
    build: .
    # 添加这个策略
    pull_policy: never
    image: chromasky-toolkit
    container_name: chromasky-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chromasky-data:/app/data
      - chromasky-outputs:/app/outputs
    env_file:
      - .env

volumes:
  chromasky-data:
  chromasky-outputs: